### ISSUE TITLE
Discussion: why removed gomonkey?

### ISSUE THREAD

**Issue by xhd2015** [kilianc/base-golang#2]
Hi @kilianc , I see in your last commit, you dropped the gomonkey dependency. Is there any specific reason you don't want to use it?

**Comment by kilianc** [comment]
@xhd2015 sorry just seeing this. The main reason why I removed it is because it didn't work consistently. I am happy to revisit the decision if the issues are addressed!

**Comment by xhd2015** [comment]
> @xhd2015 sorry just seeing this. The main reason why I removed it is because it didn't work consistently. I am happy to revisit the decision if the issues are addressed!

Huh so I know, that's also the reason I guessed.

I'll later create a PR using another stable solution( specifically the one I created: https://github.com/xhd2015/xgo), hope you can consider that. Thanks for replying.
